Anketa
KaterynaKubiedinova/anketa pull request #1
Opened 2022-09-16 13:04 UTC by KaterynaKubiedinova

2022-09-19 14:46 UTC, poulkud commented on src/components/Anketa/style.css
> +.anketa {
на английском пишем названия

2022-09-19 14:50 UTC, poulkud requested changes
Поправить табуляция( везде слетела) названия транскрипцией не пишем,  английским словом только. Поправить это и апрув. Так же на будущее коменты более информативные по названию должны быть

2022-09-19 16:01 UTC, KaterynaKubiedinova commented on src/components/Anketa/anketa.jsx
> +				<SingleLineFiled value='Сайт'/>
Табуляцию проверила, вроде ошибки исправила

2022-09-21 05:05 UTC, poulkud approved these changes

2022-09-29 14:49 UTC, merged